# Static fallback file lists (auto-generated - do not edit manually)
# To update: python scripts/update-static-fallback.py

STATIC_MITIGATION_FILES = [
    "mi-10_ai-model-version-pinning.md",
    "mi-11_human-feedback-loop-for-ai-systems.md",
    "mi-12_role-based-access-control-for-ai-data.md",
    "mi-13_providing-citations-and-source-traceability-for-ai-generated-information.md",
    "mi-14_encryption-of-ai-data-at-rest.md",
    "mi-15_using-large-language-models-for-automated-evaluation-llm-as-a-judge-.md",
    "mi-16_preserving-source-data-access-controls-in-ai-systems.md",
    "mi-17_ai-firewall-implementation-and-management.md",
    "mi-18_agent-authority-least-privilege-framework.md",
    "mi-19_tool-chain-validation-and-sanitization.md",
    "mi-1_ai-data-leakage-prevention-and-detection.md",
    "mi-20_mcp-server-security-governance.md",
    "mi-21_agent-decision-audit-and-explainability.md",
    "mi-22_multi-agent-isolation-and-segmentation.md",
    "mi-23_agentic-system-credential-protection-framework.md",
    "mi-2_data-filtering-from-external-knowledge-bases.md",
    "mi-3_user-app-model-firewalling-filtering.md",
    "mi-4_ai-system-observability.md",
    "mi-5_system-acceptance-testing.md",
    "mi-6_data-quality-classification-sensitivity.md",
    "mi-7_legal-and-contractual-frameworks-for-ai-systems.md",
    "mi-8_quality-of-service-qos-and-ddos-prevention-for-ai-systems.md",
    "mi-9_ai-system-alerting-and-denial-of-wallet-dow-spend-monitoring.md",
]

STATIC_RISK_FILES = [
    "ri-10_prompt-injection.md",
    "ri-14_inadequate-system-alignment.md",
    "ri-16_bias-and-discrimination.md",
    "ri-17_lack-of-explainability.md",
    "ri-18_model-overreach-expanded-use.md",
    "ri-19_data-quality-and-drift.md",
    "ri-1_information-leaked-to-hosted-model.md",
    "ri-20_reputational-risk.md",
    "ri-22_regulatory-compliance-and-oversight.md",
    "ri-23_intellectual-property-ip-and-copyright.md",
    "ri-24_agent-action-authorization-bypass.md",
    "ri-25_tool-chain-manipulation-and-injection.md",
    "ri-26_mcp-server-supply-chain-compromise.md",
    "ri-27_agent-state-persistence-poisoning.md",
    "ri-28_multi-agent-trust-boundary-violations.md",
    "ri-29_agent-mediated-credential-discovery-and-harvesting.md",
    "ri-2_information-leaked-to-vector-store.md",
    "ri-4_hallucination-and-inaccurate-outputs.md",
    "ri-5_foundation-model-versioning.md",
    "ri-6_non-deterministic-behaviour.md",
    "ri-7_availability-of-foundational-model.md",
    "ri-8_tampering-with-the-foundational-model.md",
    "ri-9_data-poisoning.md",
]

STATIC_FRAMEWORK_FILES = [
    "eu-ai-act.yml",
    "ffiec-itbooklets.yml",
    "iso-42001.yml",
    "nist-ai-600-1.yml",
    "nist-sp-800-53r5.yml",
    "owasp-llm.yml",
    "owasp-ml.yml",
]
