#!/bin/bash
# Development Environment Setup Script
# Sets up complete development environment for FINOS AI Governance MCP Server

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
PYTHON_VERSION="${PYTHON_VERSION:-3.11}"
VENV_PATH="${PROJECT_ROOT}/.venv"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Verify system requirements
check_requirements() {
    log_info "Checking system requirements..."
    
    # Check Python
    if ! command_exists python3; then
        log_error "Python 3 is not installed. Please install Python 3.9+ first."
        exit 1
    fi
    
    # Check Python version
    PYTHON_ACTUAL_VERSION=$(python3 --version | cut -d ' ' -f 2)
    log_info "Found Python $PYTHON_ACTUAL_VERSION"
    
    # Check git
    if ! command_exists git; then
        log_error "Git is not installed. Please install git first."
        exit 1
    fi
    
    log_success "System requirements satisfied"
}

# Create and activate virtual environment
setup_virtual_environment() {
    log_info "Setting up virtual environment..."
    
    if [[ -d "$VENV_PATH" ]]; then
        log_warning "Virtual environment already exists at $VENV_PATH"
        read -p "Remove existing environment? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$VENV_PATH"
            log_info "Removed existing virtual environment"
        else
            log_info "Using existing virtual environment"
            return 0
        fi
    fi
    
    # Create virtual environment
    python3 -m venv "$VENV_PATH"
    log_success "Virtual environment created at $VENV_PATH"
    
    # Activate virtual environment
    # shellcheck source=/dev/null
    source "$VENV_PATH/bin/activate"
    
    # Upgrade pip
    pip install --upgrade pip
    log_success "Virtual environment activated and pip upgraded"
}

# Install dependencies
install_dependencies() {
    log_info "Installing dependencies..."
    
    # Ensure virtual environment is activated
    if [[ "$VIRTUAL_ENV" != "$VENV_PATH" ]]; then
        # shellcheck source=/dev/null
        source "$VENV_PATH/bin/activate"
    fi
    
    # Install development dependencies from lock file
    if [[ -f "$PROJECT_ROOT/config/dependencies/requirements.lock" ]]; then
        log_info "Installing from requirements.lock..."
        pip install -r "$PROJECT_ROOT/config/dependencies/requirements.lock"
    else
        log_warning "requirements.lock not found, installing from pyproject.toml"
        pip install -e "[$PROJECT_ROOT]"
    fi
    
    # Install package in development mode
    pip install -e "$PROJECT_ROOT"
    
    log_success "Dependencies installed successfully"
}

# Setup pre-commit hooks
setup_pre_commit() {
    log_info "Setting up pre-commit hooks..."
    
    if [[ ! -f "$PROJECT_ROOT/config/ci/pre-commit-config.yaml" ]]; then
        log_error "Pre-commit configuration not found at config/ci/pre-commit-config.yaml"
        return 1
    fi
    
    # Install pre-commit if not already installed
    pip install pre-commit
    
    # Install hooks from the enterprise config location
    pre-commit install --config "$PROJECT_ROOT/config/ci/pre-commit-config.yaml"
    
    # Run hooks once to verify setup
    log_info "Running initial pre-commit check..."
    if pre-commit run --all-files --config "$PROJECT_ROOT/config/ci/pre-commit-config.yaml"; then
        log_success "Pre-commit hooks installed and working"
    else
        log_warning "Pre-commit hooks installed but some checks failed - this is normal for initial setup"
    fi
}

# Create development configuration
setup_dev_config() {
    log_info "Setting up development configuration..."
    
    local env_file="$PROJECT_ROOT/.env.dev"
    
    if [[ -f "$env_file" ]]; then
        log_info "Development configuration already exists at $env_file"
        return 0
    fi
    
    # Create development configuration
    cat > "$env_file" << 'EOF'
# Development Configuration for FINOS AI Governance MCP Server
# This file is automatically generated by dev-setup.sh

# Logging Configuration
FINOS_MCP_LOG_LEVEL=DEBUG
FINOS_MCP_DEBUG_MODE=true

# Network Configuration
FINOS_MCP_HTTP_TIMEOUT=10
FINOS_MCP_BASE_URL=https://raw.githubusercontent.com/finos/ai-governance-framework/main/docs

# Caching Configuration (disabled for development to see live changes)
FINOS_MCP_ENABLE_CACHE=false
FINOS_MCP_CACHE_MAX_SIZE=100
FINOS_MCP_CACHE_TTL_SECONDS=300

# GitHub API Configuration (add your token below)
# FINOS_MCP_GITHUB_TOKEN=your_token_here
FINOS_MCP_GITHUB_API_DELAY_SECONDS=1.0
FINOS_MCP_GITHUB_API_MAX_RETRIES=3

# Server Configuration
FINOS_MCP_SERVER_NAME=finos-ai-governance-dev
FINOS_MCP_SERVER_VERSION=dev
EOF
    
    log_success "Development configuration created at $env_file"
    log_info "Edit $env_file to add your GitHub token for better rate limits"
}

# Run validation tests
run_validation() {
    log_info "Running validation tests..."
    
    # Test basic import
    if python -c "import finos_mcp; print('✅ Package import successful')"; then
        log_success "Package import validation passed"
    else
        log_error "Package import validation failed"
        return 1
    fi
    
    # Test console script
    if command_exists finos-mcp; then
        log_success "Console script 'finos-mcp' available"
    else
        log_error "Console script 'finos-mcp' not found"
        return 1
    fi
    
    # Run simple functionality test if available
    if [[ -f "$PROJECT_ROOT/tests/integration/simple_test.py" ]]; then
        log_info "Running simple functionality test..."
        if python "$PROJECT_ROOT/tests/integration/simple_test.py"; then
            log_success "Simple functionality test passed"
        else
            log_warning "Simple functionality test failed - check configuration"
        fi
    fi
    
    log_success "Development environment validation completed"
}

# Print setup summary
print_summary() {
    echo
    echo "==============================================="
    echo -e "${GREEN}🎉 Development Environment Setup Complete!${NC}"
    echo "==============================================="
    echo
    echo "📁 Project structure:"
    echo "   Virtual Environment: $VENV_PATH"
    echo "   Configuration: $PROJECT_ROOT/.env.dev"
    echo "   Scripts: $PROJECT_ROOT/scripts/"
    echo
    echo "🚀 Next steps:"
    echo "   1. Activate virtual environment:"
    echo "      source .venv/bin/activate"
    echo
    echo "   2. Edit development configuration:"
    echo "      nano .env.dev"
    echo "      # Add your GitHub token for better rate limits"
    echo
    echo "   3. Test the MCP server:"
    echo "      finos-mcp --help"
    echo
    echo "   4. Run comprehensive tests:"
    echo "      python tests/run_stability_validation.py"
    echo
    echo "   5. Start development with:"
    echo "      scripts/dev-test.sh"
    echo
    echo "📚 Documentation available at:"
    echo "   docs/developer/CONTRIBUTING.md"
    echo "   docs/developer/development-guide.md"
    echo
    echo "🛠️ Development commands:"
    echo "   scripts/dev-test.sh      - Run development tests"
    echo "   scripts/quality-check.sh - Run quality validation"
    echo "   scripts/clean.sh         - Clean development artifacts"
}

# Main execution
main() {
    echo "==============================================="
    echo -e "${BLUE}🚀 FINOS AI Governance MCP Server${NC}"
    echo -e "${BLUE}   Development Environment Setup${NC}"
    echo "==============================================="
    echo
    
    cd "$PROJECT_ROOT"
    
    check_requirements
    setup_virtual_environment
    install_dependencies
    setup_pre_commit
    setup_dev_config
    run_validation
    print_summary
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi